import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Billion",
};

const LAST_UPDATED = "April 5, 2026";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing our website, joining our waitlist, or downloading and using the Billion application ('the App'), you agree to be bound by these Terms of Service. If you do not agree, do not use our services.",
  },
  {
    title: "2. Description of Service",
    body: "Billion provides AI-generated summaries and analyses of publicly available government documents for informational and civic-education purposes only. This is not legal, financial, or professional advice. Always verify information through primary sources.",
  },
  {
    title: "3. Eligibility",
    body: "You must be at least 13 years of age to use our services. If you are under 18, you represent that you have obtained parental or guardian consent.",
  },
  {
    title: "4. Prohibited Conduct",
    body: "You agree not to: (a) reverse-engineer or decompile any part of the App; (b) interfere with or disrupt our infrastructure; (c) scrape or harvest data using automated means; or (d) use the App to distribute misleading or unlawful content.",
  },
  {
    title: "5. Intellectual Property",
    body: "All original content, design, and software are the property of Billion and protected by applicable intellectual property laws. Government documents are in the public domain. You receive a limited, non-exclusive, non-transferable license for personal, non-commercial use only.",
  },
  {
    title: "6. AI-Generated Content Disclaimer",
    body: "Summaries are generated by automated AI and may contain errors or omissions. Billion is not liable for decisions made in reliance on AI-generated content.",
  },
  {
    title: "7. Disclaimer of Warranties",
    body: "THE APP IS PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.",
  },
  {
    title: "8. Limitation of Liability",
    body: "TO THE FULLEST EXTENT PERMITTED BY LAW, BILLION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OUR SERVICES.",
  },
  {
    title: "9. Governing Law",
    body: "These Terms are governed by the laws of the State of California, without regard to conflict-of-law principles.",
  },
  {
    title: "10. Changes to These Terms",
    body: "We may update these Terms at any time. Material changes will be communicated via in-app notice or email. Continued use of our services after changes constitutes acceptance.",
  },
  {
    title: "11. Contact",
    body: "Questions about these Terms? Email us at thatxliner@gmail.com.",
  },
];

export default function TermsPage() {
  return (
    <main className="bg-background text-foreground min-h-screen">
      <nav
        className="mx-auto flex items-center justify-between px-6 py-5"
        style={{ maxWidth: 1120 }}
      >
        <Link
          href="/"
          className="text-foreground font-display text-[22px] font-bold tracking-[-0.02em] no-underline"
        >
          Billion
        </Link>
        <Link
          href="/privacy"
          className="text-muted-foreground hover:text-accent font-sans text-[15px] font-medium no-underline transition-colors duration-200"
        >
          Privacy Policy
        </Link>
      </nav>

      <article
        className="mx-auto px-6 py-12 md:py-16"
        style={{ maxWidth: 720 }}
      >
        <p className="tracking-label text-muted-foreground mb-2 font-sans text-[12px] font-medium uppercase">
          Last updated {LAST_UPDATED}
        </p>
        <h1
          className="text-foreground font-display mb-10 leading-[1.15] font-bold tracking-[-0.02em]"
          style={{ fontSize: "clamp(2rem, 4vw, 3rem)" }}
        >
          Terms of Service
        </h1>

        <div className="flex flex-col gap-8">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="text-foreground mb-2 font-sans text-[15px] font-semibold">
                {s.title}
              </h2>
              <p className="text-muted-foreground m-0 font-sans text-[16px] leading-[1.7]">
                {s.body}
              </p>
            </section>
          ))}
        </div>
      </article>

      <footer
        className="border-border mx-auto flex items-center justify-between border-t px-6 py-8"
        style={{ maxWidth: 1120 }}
      >
        <span className="text-muted-foreground font-display text-[18px] font-bold">
          Billion
        </span>
        <div className="flex items-center gap-5 font-sans text-[13px]">
          <Link
            href="/terms"
            className="text-muted-foreground hover:text-accent no-underline transition-colors duration-200"
          >
            Terms
          </Link>
          <Link
            href="/privacy"
            className="text-muted-foreground hover:text-accent no-underline transition-colors duration-200"
          >
            Privacy
          </Link>
          <span className="text-muted-foreground/70">
            &copy; 2026 Billion. All rights reserved.
          </span>
        </div>
      </footer>
    </main>
  );
}
