import { ScrollView, StyleSheet, TouchableOpacity } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

import { Text, View } from "~/components/Themed";
import { colors, fonts, sp, useTheme, type Theme } from "~/styles";

const LAST_UPDATED = "April 5, 2026";

const TERMS_SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing our website, joining our waitlist, or downloading and using the Billion application ('the App'), you agree to be bound by these Terms of Service. If you do not agree, do not use our services.",
  },
  {
    title: "2. Description of Service",
    body: "Billion provides AI-generated summaries and analyses of publicly available government documents for informational and civic-education purposes only. This is not legal, financial, or professional advice. Always verify information through primary sources.",
  },
  {
    title: "3. Eligibility",
    body: "You must be at least 13 years of age to use our services. If you are under 18, you represent that you have obtained parental or guardian consent.",
  },
  {
    title: "4. Prohibited Conduct",
    body: "You agree not to: (a) reverse-engineer or decompile any part of the App; (b) interfere with or disrupt our infrastructure; (c) scrape or harvest data using automated means; or (d) use the App to distribute misleading or unlawful content.",
  },
  {
    title: "5. Intellectual Property",
    body: "All original content, design, and software are the property of Billion and protected by applicable intellectual property laws. Government documents are in the public domain. You receive a limited, non-exclusive, non-transferable license for personal, non-commercial use only.",
  },
  {
    title: "6. AI-Generated Content Disclaimer",
    body: "Summaries are generated by automated AI and may contain errors or omissions. Billion is not liable for decisions made in reliance on AI-generated content.",
  },
  {
    title: "7. Disclaimer of Warranties",
    body: "THE APP IS PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.",
  },
  {
    title: "8. Limitation of Liability",
    body: "TO THE FULLEST EXTENT PERMITTED BY LAW, BILLION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OUR SERVICES.",
  },
  {
    title: "9. Governing Law",
    body: "These Terms are governed by the laws of the State of California, without regard to conflict-of-law principles.",
  },
  {
    title: "10. Changes to These Terms",
    body: "We may update these Terms at any time. Material changes will be communicated via in-app notice or email. Continued use of our services after changes constitutes acceptance.",
  },
  {
    title: "11. Contact",
    body: "Questions about these Terms? Email us at Thatxliner@gmail.com.",
  },
];

const PRIVACY_SECTIONS = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly, including your email address when you join our waitlist or create an account, and any preferences or profile information you submit. We also collect information automatically when you use our services, such as usage data, device type, and app interactions.",
  },
  {
    title: "2. Waitlist and Landing Page",
    body: "When you sign up for our waitlist, we collect your email address to notify you when the App becomes available and to send updates about Billion. You can unsubscribe at any time by emailing Thatxliner@gmail.com.",
  },
  {
    title: "3. How We Use Your Information",
    body: "We use collected information to operate and improve our services, personalize your experience, send service-related and waitlist communications, and comply with legal obligations. We do not sell your personal information.",
  },
  {
    title: "4. Data Sharing",
    body: "We may share your information with service providers who assist us in operating our services (e.g. hosting, analytics, email delivery). We require all third parties to respect the security of your data and not use it for their own marketing purposes.",
  },
  {
    title: "5. Your Choices",
    body: "You can control certain data uses — including analytics and personalized content — through Privacy Settings in the app. You may request access to or deletion of your personal data at any time by emailing Thatxliner@gmail.com.",
  },
  {
    title: "6. Data Retention",
    body: "We retain your information for as long as your account is active or as needed to provide our services. Waitlist email addresses are retained until you unsubscribe or request deletion.",
  },
  {
    title: "7. Security",
    body: "We implement commercially reasonable security measures to protect your data. No internet transmission or electronic storage is 100% secure.",
  },
  {
    title: "8. Children's Privacy",
    body: "Our services are not directed at children under 13. We do not knowingly collect personal information from children under 13. If we become aware we have done so, we will delete it promptly.",
  },
  {
    title: "9. Changes to This Policy",
    body: "We may update this Privacy Policy from time to time. We will notify you of material changes via in-app notice or email.",
  },
  {
    title: "10. Contact",
    body: "Questions about this Privacy Policy or your data? Email us at Thatxliner@gmail.com.",
  },
];

function DocSection({ title, body, theme }: { title: string; body: string; theme: Theme }) {
  return (
    <View style={styles.section} lightColor="transparent" darkColor="transparent">
      <Text style={[styles.sectionTitle, { color: theme.foreground }]}>{title}</Text>
      <Text style={[styles.sectionBody, { color: theme.textSecondary }]}>{body}</Text>
    </View>
  );
}

export default function TermsScreen() {
  const router = useRouter();
  const { theme } = useTheme();

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: theme.background }]} edges={["top"]}>
      <View
        style={[styles.header, { borderBottomColor: theme.border, backgroundColor: theme.background }]}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          style={styles.backBtn}
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Ionicons name="chevron-back" size={22} color={colors.white} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: theme.foreground }]}>Terms & Privacy</Text>
        <View style={{ width: 44 }} lightColor="transparent" darkColor="transparent" />
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>
        <Text style={[styles.lastUpdated, { color: theme.mutedForeground }]}>
          Last updated {LAST_UPDATED}
        </Text>

        <Text style={[styles.docTitle, { color: theme.foreground }]}>Terms of Service</Text>
        {TERMS_SECTIONS.map((s) => (
          <DocSection key={s.title} {...s} theme={theme} />
        ))}

        <View style={[styles.divider, { backgroundColor: theme.border }]} lightColor={theme.border} darkColor={theme.border} />

        <Text style={[styles.docTitle, { color: theme.foreground }]}>Privacy Policy</Text>
        {PRIVACY_SECTIONS.map((s) => (
          <DocSection key={s.title} {...s} theme={theme} />
        ))}

        <View style={{ height: sp[10] }} lightColor="transparent" darkColor="transparent" />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: sp[4],
    paddingVertical: sp[4],
    borderBottomWidth: 1,
  },
  backBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    flex: 1,
    textAlign: "center",
    fontFamily: fonts.bodySemibold,
    fontSize: 16,
  },
  scroll: { flex: 1, paddingHorizontal: sp[5] },
  lastUpdated: {
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: sp[5],
    marginBottom: sp[6],
  },
  docTitle: {
    fontFamily: fonts.bodySemibold,
    fontSize: 20,
    marginBottom: sp[5],
  },
  divider: {
    height: 1,
    marginVertical: sp[8],
  },
  section: {
    marginBottom: sp[6],
  },
  sectionTitle: {
    fontFamily: fonts.bodySemibold,
    fontSize: 14,
    marginBottom: sp[2],
  },
  sectionBody: {
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 21,
  },
});
