/**
 * Supreme Court (SCOTUS) Case Scraper
 *
 * Fetches case data from the Supreme Court's official website
 * (supremecourt.gov) and the CourtListener REST API, which provides
 * structured JSON for opinions, docket entries, and case metadata.
 *
 * CourtListener API: https://www.courtlistener.com/api/rest/v4/
 * Free, no API key required for basic usage.
 * Optional: set COURTLISTENER_API_KEY for higher rate limits.
 *
 * For each case we fetch:
 *   - Case name, docket number, court, filing date, status
 *   - A plain-text excerpt of the opinion (used as fullText)
 *   - A short description generated by the existing generateAISummary utility
 */

import { printMetricsSummary, resetMetrics } from "../utils/db/metrics.js";
import { upsertCourtCase } from "../utils/db/operations.js";

const CL_BASE = "https://www.courtlistener.com/api/rest/v4";

// ─── Config ──────────────────────────────────────────────────────────────────

export interface ScotusScraperConfig {
  maxCases?: number;  // Default: 50
  /** CourtListener court ID. "scotus" for Supreme Court, "ca9" for 9th Circuit, etc. */
  court?: string;     // Default: "scotus"
}

// ─── API response shapes (partial) ───────────────────────────────────────────

interface ClCluster {
  id: number;
  absolute_url: string;
  case_name: string;
  docket_id: number;
  date_filed: string | null;
  date_blocked: string | null;
  precedential_status: string; // "Published", "Unpublished", etc.
  syllabus: string;            // Short summary (may be HTML)
  plain_text: string;
  download_url: string | null;
  sub_opinions: string[];      // URLs to individual opinion objects
}

interface ClOpinion {
  id: number;
  plain_text: string;
  html: string;
  type: string; // "010combined", "020lead", "030concurrence", "040dissent"
}

interface ClDocket {
  id: number;
  docket_number: string;
  court: string;               // e.g. "scotus"
  date_filed: string | null;
  case_name: string;
  pacer_case_id: string | null;
  clusters: string[];          // URLs to opinion clusters
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function clHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    "Accept": "application/json",
    "User-Agent": "billion-scraper/1.0 (contact via github)",
  };
  if (process.env.COURTLISTENER_API_KEY) {
    headers["Authorization"] = `Token ${process.env.COURTLISTENER_API_KEY}`;
  }
  return headers;
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function clFetch<T>(path: string, params: Record<string, string | number> = {}): Promise<T> {
  const url = new URL(`${CL_BASE}${path}`);
  for (const [k, v] of Object.entries(params)) {
    url.searchParams.set(k, String(v));
  }

  const maxRetries = 3;
  const baseBackoffMs = 1000;      // 1s base backoff
  const requestTimeoutMs = 30000;  // 30s per-attempt timeout

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), requestTimeoutMs);

    try {
      const res = await fetch(url.toString(), {
        headers: clHeaders(),
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (res.ok) {
        return res.json() as Promise<T>;
      }

      const status = res.status;

      // Handle rate limiting (429) and transient server errors (5xx) with retries.
      if ((status === 429 || (status >= 500 && status < 600)) && attempt < maxRetries) {
        let delayMs = baseBackoffMs * Math.pow(2, attempt); // exponential backoff

        if (status === 429) {
          const retryAfter = res.headers.get("Retry-After");
          if (retryAfter) {
            const seconds = Number(retryAfter);
            if (!Number.isNaN(seconds)) {
              delayMs = Math.max(delayMs, seconds * 1000);
            } else {
              const retryDate = new Date(retryAfter).getTime();
              if (!Number.isNaN(retryDate)) {
                const candidate = retryDate - Date.now();
                if (candidate > 0) {
                  delayMs = Math.max(delayMs, candidate);
                }
              }
            }
          }
        }

        await delay(delayMs);
        continue;
      }

      // Non-retryable HTTP status: throw immediately.
      throw new Error(`CourtListener ${path} → HTTP ${status}`);
    } catch (err: any) {
      clearTimeout(timeoutId);

      const isAbortError = err && (err.name === "AbortError" || err.code === "ABORT_ERR");

      // Retry on abort/timeouts and generic network errors, up to maxRetries.
      if (attempt < maxRetries && (isAbortError || err?.name === "FetchError" || err?.code === "ECONNRESET" || err?.code === "ECONNREFUSED")) {
        const delayMs = baseBackoffMs * Math.pow(2, attempt);
        await delay(delayMs);
        continue;
      }

      // Out of retries or non-retryable error: rethrow.
      throw err;
    }
  }

  // We should never get here because the loop either returns or throws.
  throw new Error(`CourtListener ${path} → failed after ${maxRetries + 1} attempts`);
}

/** Strip basic HTML and collapse whitespace */
function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s{2,}/g, " ")
    .trim();
}

/** Truncate to N words */
function truncateWords(text: string, maxWords: number): string {
  const words = text.split(/\s+/);
  return words.length > maxWords ? words.slice(0, maxWords).join(" ") : text;
}

/**
 * Attempt to download the plain-text opinion from CourtListener sub-opinion objects.
 * Returns the first non-empty lead/combined opinion text, truncated to 1,000 words.
 */
async function fetchOpinionText(subOpinionUrls: string[]): Promise<string | undefined> {
  // Fetch all available sub-opinions, then prefer lead/combined types.
  const fetched: { opinion: ClOpinion; text: string }[] = [];

  for (const url of subOpinionUrls) {
    try {
      const res = await fetch(url, { headers: clHeaders() });
      if (!res.ok) continue;
      const opinion = await res.json() as ClOpinion;
      // Prefer plain text; fall back to stripping HTML
      const text = (opinion.plain_text?.trim() || stripHtml(opinion.html ?? "")).trim();
      if (text.length === 0) continue;
      fetched.push({ opinion, text });
    } catch {
      continue;
    }
  }

  if (fetched.length === 0) {
    return undefined;
  }

  const preferredTypes = new Set<string>(["010combined", "020lead"]);

  fetched.sort((a, b) => {
    const aPref = preferredTypes.has(a.opinion.type) ? 0 : 1;
    const bPref = preferredTypes.has(b.opinion.type) ? 0 : 1;
    if (aPref !== bPref) return aPref - bPref;
    // Stable within the same preference group; leave original order otherwise.
    return 0;
  });

  for (const { text } of fetched) {
    if (text.length > 200) {
      return truncateWords(text, 1000);
    }
  }
  return undefined;
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function scrapeScotus(config: ScotusScraperConfig = {}) {
  const {
    maxCases = 50,
    court = "scotus",
  } = config;

  console.log(`Starting CourtListener scraper (court=${court}, maxCases=${maxCases})...`);
  resetMetrics();

  // ── Step 1: fetch recent opinion clusters for the target court ─────────────
  const data = await clFetch<{ results: ClCluster[]; count: number }>(
    "/clusters/",
    {
      court: court,
      order_by: "-date_filed",
      page_size: Math.min(maxCases, 100),
    }
  );

  const clusters = (data.results ?? []).slice(0, maxCases);
  console.log(`Fetched ${clusters.length} opinion clusters.`);

  // ── Step 2: process each cluster ───────────────────────────────────────────
  for (const cluster of clusters) {
    try {
      // Fetch docket for case number + court metadata
      let docketNumber = `CL-${cluster.id}`;
      let filedDate: Date | undefined;
      let courtSlug = court;

      const docket = await clFetch<ClDocket>(`/dockets/${cluster.docket_id}/`);
      docketNumber = docket.docket_number || docketNumber;
      if (docket.date_filed) filedDate = new Date(docket.date_filed);
      courtSlug = docket.court ?? court;

      // Map CourtListener court IDs to readable names
      const courtNames: Record<string, string> = {
        scotus: "Supreme Court of the United States",
        ca1: "1st Circuit Court of Appeals",
        ca2: "2nd Circuit Court of Appeals",
        ca3: "3rd Circuit Court of Appeals",
        ca4: "4th Circuit Court of Appeals",
        ca5: "5th Circuit Court of Appeals",
        ca6: "6th Circuit Court of Appeals",
        ca7: "7th Circuit Court of Appeals",
        ca8: "8th Circuit Court of Appeals",
        ca9: "9th Circuit Court of Appeals",
        ca10: "10th Circuit Court of Appeals",
        ca11: "11th Circuit Court of Appeals",
        cadc: "D.C. Circuit Court of Appeals",
      };
      const courtName = courtNames[courtSlug] ?? courtSlug.toUpperCase();

      const title = cluster.case_name?.slice(0, 250) || "Unknown Case";
      const status = cluster.precedential_status || "Unknown";
      const caseUrl = `https://www.courtlistener.com${cluster.absolute_url}`;

      // Plain-text opinion (used for AI article generation downstream)
      const fullText = await fetchOpinionText(cluster.sub_opinions ?? []);

      // Use syllabus as description if available (it's a short court-written summary)
      const description = cluster.syllabus
        ? stripHtml(cluster.syllabus).slice(0, 1000) || undefined
        : undefined;

      await upsertCourtCase({
        caseNumber: docketNumber,
        title,
        court: courtName,
        filedDate,
        description,
        status,
        fullText,
        url: caseUrl,
      });

      console.log(`Processed: ${docketNumber} — ${title}`);
    } catch (error) {
      console.error(`Error processing cluster ${cluster.id}:`, error);
    }
  }

  console.log("CourtListener scraper completed.");
  printMetricsSummary(courtId(court));
}

function courtId(court: string): string {
  return court === "scotus" ? "SCOTUS" : court.toUpperCase();
}